version: '3.8'

services:

  # Redis缓存和消息队列
  redis:
    image: redis:7-alpine


  # Django后端
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - REDIS_HOST=redis
    depends_on:
      - redis

  # Celery Worker
  celery:
    image: ai_story-backend
    command: celery -A config worker -l info
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - REDIS_HOST=redis
    depends_on:
      - redis

  # Vue前端
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

